version: '3'

dotenv: ['vars.env']

includes:
  docker:
    taskfile: tasks/Taskfile.docker.yml
    dir: .
    optional: true
  cli:
    taskfile: tasks/Taskfile.cli.yml
    dir: .
    optional: true
tasks:

