version: '3'

tasks:
  setup:mac:
    desc: "Install required CLI tools on macOS"
    silent: true
    cmds:
      - brew install awscli || true
      - brew install opentofu || true
      - brew install infracost || true
      - brew install tailscale || true
      - brew install google-cloud-sdk || true

  tofu:init:
    desc: "Initialize OpenTofu"
    silent: true
    dir: infra/{{.CLOUD | default "aws"}}
    cmds:
      - tofu init

  tofu:plan:
    desc: "Create a plan"
    silent: true
    dir: infra/{{.CLOUD | default "aws"}}
    cmds:
      - mkdir -p .tfplan
      - tofu plan -out .tfplan/plan.tfplan

  tofu:show-json:
    desc: "Generate plan JSON"
    silent: true
    dir: infra/{{.CLOUD | default "aws"}}
    cmds:
      - tofu show -json .tfplan/plan.tfplan > .tfplan/plan.json

  tofu:apply:
    desc: "Apply the plan"
    silent: true
    dir: infra/{{.CLOUD | default "aws"}}
    cmds:
      - tofu apply -auto-approve .tfplan/plan.tfplan

  cost:breakdown:
    desc: "Show cost estimate for the current plan"
    silent: true
    dir: infra/{{.CLOUD | default "aws"}}
    cmds:
      - infracost breakdown --path .tfplan/plan.json

  create:
    desc: "Provision the stack and show cost estimate"
    silent: true
    cmds:
      - task: tofu:init
      - task: tofu:plan
      - task: tofu:show-json
      - task: tofu:apply
      - task: cost:breakdown

  destroy:
    desc: "Destroy the stack"
    silent: true
    dir: infra/{{.CLOUD | default "aws"}}
    cmds:
      - tofu destroy -auto-approve

  status:
    desc: "Show the instance state"
    silent: true
    dir: infra/{{.CLOUD | default "aws"}}
    cmds:
      - tofu output -raw instance_status

  start:
    desc: "Start the instance if it is stopped"
    silent: true
    dir: infra/{{.CLOUD | default "aws"}}
    cmds:
      - tofu apply -auto-approve -var desired_state=running

  stop:
    desc: "Stop the instance if it is running"
    silent: true
    dir: infra/{{.CLOUD | default "aws"}}
    cmds:
      - tofu apply -auto-approve -var desired_state=stopped


