version: '3'

vars:
  IMAGE_NAME: ollama-tools:latest

tasks:
  build:
    desc: "Build the all-in-one tools image"
    silent: true
    cmds:
      - docker build -t {{.IMAGE_NAME}} -f Dockerfile .

  create:
    desc: "Create (init, plan, apply, cost) using the tools image"
    silent: true
    cmds:
      - task: build
      - docker run --rm --env-file vars.env \
          -v "$PWD:/work" \
          -v "$HOME/.aws:/root/.aws:ro" \
          -v "$HOME/.gcp/creds.json:/work/.gcp/creds.json:ro" \
          -w /work/infra/${CLOUD:-aws} \
          {{.IMAGE_NAME}} /usr/local/bin/scripts/create.sh

  destroy:
    desc: "Destroy using the tools image"
    silent: true
    cmds:
      - task: build
      - docker run --rm --env-file vars.env \
          -v "$PWD:/work" \
          -v "$HOME/.aws:/root/.aws:ro" \
          -v "$HOME/.gcp/creds.json:/work/.gcp/creds.json:ro" \
          -w /work/infra/${CLOUD:-aws} \
          {{.IMAGE_NAME}} /usr/local/bin/scripts/destroy.sh

  start:
    desc: "Start the instance if stopped"
    silent: true
    cmds:
      - task: build
      - docker run --rm --env-file vars.env \
          -v "$PWD:/work" \
          -v "$HOME/.aws:/root/.aws:ro" \
          -v "$HOME/.gcp/creds.json:/work/.gcp/creds.json:ro" \
          -w /work/infra/${CLOUD:-aws} \
          {{.IMAGE_NAME}} /usr/local/bin/scripts/start.sh

  stop:
    desc: "Stop the instance if running"
    silent: true
    cmds:
      - task: build
      - docker run --rm --env-file vars.env \
          -v "$PWD:/work" \
          -v "$HOME/.aws:/root/.aws:ro" \
          -v "$HOME/.gcp/creds.json:/work/.gcp/creds.json:ro" \
          -w /work/infra/${CLOUD:-aws} \
          {{.IMAGE_NAME}} /usr/local/bin/scripts/stop.sh

  status:
    desc: "Show instance status using the tools image"
    silent: true
    cmds:
      - task: build
      - docker run --rm --env-file vars.env \
          -v "$PWD:/work" \
          -v "$HOME/.aws:/root/.aws:ro" \
          -v "$HOME/.gcp/creds.json:/work/.gcp/creds.json:ro" \
          -w /work/infra/${CLOUD:-aws} \
          {{.IMAGE_NAME}} /usr/local/bin/scripts/status.sh


